/*
 * Copyright 2021 Artem Godin.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Dependency-Track API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.fluorumlabs.dtrack.model.Component;
import com.github.fluorumlabs.dtrack.model.DependencyMetrics;
import com.github.fluorumlabs.dtrack.model.License;
import com.github.fluorumlabs.dtrack.model.PackageURL;
import com.github.fluorumlabs.dtrack.model.Project;
import com.github.fluorumlabs.dtrack.model.RepositoryMetaComponent;
import com.github.fluorumlabs.dtrack.model.Vulnerability;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Component
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-21T09:42:21.596Z")
public class Component {
  @SerializedName("author")
  private String author = null;

  @SerializedName("publisher")
  private String publisher = null;

  @SerializedName("group")
  private String group = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("version")
  private String version = null;

  /**
   * Gets or Sets classifier
   */
  @JsonAdapter(ClassifierEnum.Adapter.class)
  public enum ClassifierEnum {
    APPLICATION("APPLICATION"),
    
    FRAMEWORK("FRAMEWORK"),
    
    LIBRARY("LIBRARY"),
    
    CONTAINER("CONTAINER"),
    
    OPERATING_SYSTEM("OPERATING_SYSTEM"),
    
    DEVICE("DEVICE"),
    
    FIRMWARE("FIRMWARE"),
    
    FILE("FILE");

    private String value;

    ClassifierEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ClassifierEnum fromValue(String text) {
      for (ClassifierEnum b : ClassifierEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ClassifierEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ClassifierEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ClassifierEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ClassifierEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("classifier")
  private ClassifierEnum classifier = null;

  @SerializedName("filename")
  private String filename = null;

  @SerializedName("extension")
  private String extension = null;

  @SerializedName("md5")
  private String md5 = null;

  @SerializedName("sha1")
  private String sha1 = null;

  @SerializedName("sha256")
  private String sha256 = null;

  @SerializedName("sha384")
  private String sha384 = null;

  @SerializedName("sha512")
  private String sha512 = null;

  @SerializedName("sha3_256")
  private String sha3256 = null;

  @SerializedName("sha3_384")
  private String sha3384 = null;

  @SerializedName("sha3_512")
  private String sha3512 = null;

  @SerializedName("blake2b_256")
  private String blake2b256 = null;

  @SerializedName("blake2b_384")
  private String blake2b384 = null;

  @SerializedName("blake2b_512")
  private String blake2b512 = null;

  @SerializedName("blake3")
  private String blake3 = null;

  @SerializedName("cpe")
  private String cpe = null;

  @SerializedName("purl")
  private PackageURL purl = null;

  @SerializedName("purlCoordinates")
  private PackageURL purlCoordinates = null;

  @SerializedName("swidTagId")
  private String swidTagId = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("copyright")
  private String copyright = null;

  @SerializedName("license")
  private String license = null;

  @SerializedName("resolvedLicense")
  private License resolvedLicense = null;

  @SerializedName("directDependencies")
  private String directDependencies = null;

  @SerializedName("parent")
  private Component parent = null;

  @SerializedName("children")
  private List<Component> children = null;

  @SerializedName("vulnerabilities")
  private List<Vulnerability> vulnerabilities = null;

  @SerializedName("project")
  private Project project = null;

  @SerializedName("lastInheritedRiskScore")
  private Double lastInheritedRiskScore = null;

  @SerializedName("notes")
  private String notes = null;

  @SerializedName("uuid")
  private UUID uuid = null;

  @SerializedName("bomRef")
  private String bomRef = null;

  @SerializedName("metrics")
  private DependencyMetrics metrics = null;

  @SerializedName("repositoryMeta")
  private RepositoryMetaComponent repositoryMeta = null;

  @SerializedName("usedBy")
  private Integer usedBy = null;

  @SerializedName("isInternal")
  private Boolean isInternal = null;

  public Component author(String author) {
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @ApiModelProperty(value = "")
  public String getAuthor() {
    return author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public Component publisher(String publisher) {
    this.publisher = publisher;
    return this;
  }

   /**
   * Get publisher
   * @return publisher
  **/
  @ApiModelProperty(value = "")
  public String getPublisher() {
    return publisher;
  }

  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }

  public Component group(String group) {
    this.group = group;
    return this;
  }

   /**
   * Get group
   * @return group
  **/
  @ApiModelProperty(value = "")
  public String getGroup() {
    return group;
  }

  public void setGroup(String group) {
    this.group = group;
  }

  public Component name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Component version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public Component classifier(ClassifierEnum classifier) {
    this.classifier = classifier;
    return this;
  }

   /**
   * Get classifier
   * @return classifier
  **/
  @ApiModelProperty(value = "")
  public ClassifierEnum getClassifier() {
    return classifier;
  }

  public void setClassifier(ClassifierEnum classifier) {
    this.classifier = classifier;
  }

  public Component filename(String filename) {
    this.filename = filename;
    return this;
  }

   /**
   * Get filename
   * @return filename
  **/
  @ApiModelProperty(value = "")
  public String getFilename() {
    return filename;
  }

  public void setFilename(String filename) {
    this.filename = filename;
  }

  public Component extension(String extension) {
    this.extension = extension;
    return this;
  }

   /**
   * Get extension
   * @return extension
  **/
  @ApiModelProperty(value = "")
  public String getExtension() {
    return extension;
  }

  public void setExtension(String extension) {
    this.extension = extension;
  }

  public Component md5(String md5) {
    this.md5 = md5;
    return this;
  }

   /**
   * Get md5
   * @return md5
  **/
  @ApiModelProperty(value = "")
  public String getMd5() {
    return md5;
  }

  public void setMd5(String md5) {
    this.md5 = md5;
  }

  public Component sha1(String sha1) {
    this.sha1 = sha1;
    return this;
  }

   /**
   * Get sha1
   * @return sha1
  **/
  @ApiModelProperty(value = "")
  public String getSha1() {
    return sha1;
  }

  public void setSha1(String sha1) {
    this.sha1 = sha1;
  }

  public Component sha256(String sha256) {
    this.sha256 = sha256;
    return this;
  }

   /**
   * Get sha256
   * @return sha256
  **/
  @ApiModelProperty(value = "")
  public String getSha256() {
    return sha256;
  }

  public void setSha256(String sha256) {
    this.sha256 = sha256;
  }

  public Component sha384(String sha384) {
    this.sha384 = sha384;
    return this;
  }

   /**
   * Get sha384
   * @return sha384
  **/
  @ApiModelProperty(value = "")
  public String getSha384() {
    return sha384;
  }

  public void setSha384(String sha384) {
    this.sha384 = sha384;
  }

  public Component sha512(String sha512) {
    this.sha512 = sha512;
    return this;
  }

   /**
   * Get sha512
   * @return sha512
  **/
  @ApiModelProperty(value = "")
  public String getSha512() {
    return sha512;
  }

  public void setSha512(String sha512) {
    this.sha512 = sha512;
  }

  public Component sha3256(String sha3256) {
    this.sha3256 = sha3256;
    return this;
  }

   /**
   * Get sha3256
   * @return sha3256
  **/
  @ApiModelProperty(value = "")
  public String getSha3256() {
    return sha3256;
  }

  public void setSha3256(String sha3256) {
    this.sha3256 = sha3256;
  }

  public Component sha3384(String sha3384) {
    this.sha3384 = sha3384;
    return this;
  }

   /**
   * Get sha3384
   * @return sha3384
  **/
  @ApiModelProperty(value = "")
  public String getSha3384() {
    return sha3384;
  }

  public void setSha3384(String sha3384) {
    this.sha3384 = sha3384;
  }

  public Component sha3512(String sha3512) {
    this.sha3512 = sha3512;
    return this;
  }

   /**
   * Get sha3512
   * @return sha3512
  **/
  @ApiModelProperty(value = "")
  public String getSha3512() {
    return sha3512;
  }

  public void setSha3512(String sha3512) {
    this.sha3512 = sha3512;
  }

  public Component blake2b256(String blake2b256) {
    this.blake2b256 = blake2b256;
    return this;
  }

   /**
   * Get blake2b256
   * @return blake2b256
  **/
  @ApiModelProperty(value = "")
  public String getBlake2b256() {
    return blake2b256;
  }

  public void setBlake2b256(String blake2b256) {
    this.blake2b256 = blake2b256;
  }

  public Component blake2b384(String blake2b384) {
    this.blake2b384 = blake2b384;
    return this;
  }

   /**
   * Get blake2b384
   * @return blake2b384
  **/
  @ApiModelProperty(value = "")
  public String getBlake2b384() {
    return blake2b384;
  }

  public void setBlake2b384(String blake2b384) {
    this.blake2b384 = blake2b384;
  }

  public Component blake2b512(String blake2b512) {
    this.blake2b512 = blake2b512;
    return this;
  }

   /**
   * Get blake2b512
   * @return blake2b512
  **/
  @ApiModelProperty(value = "")
  public String getBlake2b512() {
    return blake2b512;
  }

  public void setBlake2b512(String blake2b512) {
    this.blake2b512 = blake2b512;
  }

  public Component blake3(String blake3) {
    this.blake3 = blake3;
    return this;
  }

   /**
   * Get blake3
   * @return blake3
  **/
  @ApiModelProperty(value = "")
  public String getBlake3() {
    return blake3;
  }

  public void setBlake3(String blake3) {
    this.blake3 = blake3;
  }

  public Component cpe(String cpe) {
    this.cpe = cpe;
    return this;
  }

   /**
   * Get cpe
   * @return cpe
  **/
  @ApiModelProperty(value = "")
  public String getCpe() {
    return cpe;
  }

  public void setCpe(String cpe) {
    this.cpe = cpe;
  }

  public Component purl(PackageURL purl) {
    this.purl = purl;
    return this;
  }

   /**
   * Get purl
   * @return purl
  **/
  @ApiModelProperty(value = "")
  public PackageURL getPurl() {
    return purl;
  }

  public void setPurl(PackageURL purl) {
    this.purl = purl;
  }

  public Component purlCoordinates(PackageURL purlCoordinates) {
    this.purlCoordinates = purlCoordinates;
    return this;
  }

   /**
   * Get purlCoordinates
   * @return purlCoordinates
  **/
  @ApiModelProperty(value = "")
  public PackageURL getPurlCoordinates() {
    return purlCoordinates;
  }

  public void setPurlCoordinates(PackageURL purlCoordinates) {
    this.purlCoordinates = purlCoordinates;
  }

  public Component swidTagId(String swidTagId) {
    this.swidTagId = swidTagId;
    return this;
  }

   /**
   * Get swidTagId
   * @return swidTagId
  **/
  @ApiModelProperty(value = "")
  public String getSwidTagId() {
    return swidTagId;
  }

  public void setSwidTagId(String swidTagId) {
    this.swidTagId = swidTagId;
  }

  public Component description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Component copyright(String copyright) {
    this.copyright = copyright;
    return this;
  }

   /**
   * Get copyright
   * @return copyright
  **/
  @ApiModelProperty(value = "")
  public String getCopyright() {
    return copyright;
  }

  public void setCopyright(String copyright) {
    this.copyright = copyright;
  }

  public Component license(String license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  @ApiModelProperty(value = "")
  public String getLicense() {
    return license;
  }

  public void setLicense(String license) {
    this.license = license;
  }

  public Component resolvedLicense(License resolvedLicense) {
    this.resolvedLicense = resolvedLicense;
    return this;
  }

   /**
   * Get resolvedLicense
   * @return resolvedLicense
  **/
  @ApiModelProperty(value = "")
  public License getResolvedLicense() {
    return resolvedLicense;
  }

  public void setResolvedLicense(License resolvedLicense) {
    this.resolvedLicense = resolvedLicense;
  }

  public Component directDependencies(String directDependencies) {
    this.directDependencies = directDependencies;
    return this;
  }

   /**
   * Get directDependencies
   * @return directDependencies
  **/
  @ApiModelProperty(value = "")
  public String getDirectDependencies() {
    return directDependencies;
  }

  public void setDirectDependencies(String directDependencies) {
    this.directDependencies = directDependencies;
  }

  public Component parent(Component parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @ApiModelProperty(value = "")
  public Component getParent() {
    return parent;
  }

  public void setParent(Component parent) {
    this.parent = parent;
  }

  public Component children(List<Component> children) {
    this.children = children;
    return this;
  }

  public Component addChildrenItem(Component childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  @ApiModelProperty(value = "")
  public List<Component> getChildren() {
    return children;
  }

  public void setChildren(List<Component> children) {
    this.children = children;
  }

  public Component vulnerabilities(List<Vulnerability> vulnerabilities) {
    this.vulnerabilities = vulnerabilities;
    return this;
  }

  public Component addVulnerabilitiesItem(Vulnerability vulnerabilitiesItem) {
    if (this.vulnerabilities == null) {
      this.vulnerabilities = new ArrayList<>();
    }
    this.vulnerabilities.add(vulnerabilitiesItem);
    return this;
  }

   /**
   * Get vulnerabilities
   * @return vulnerabilities
  **/
  @ApiModelProperty(value = "")
  public List<Vulnerability> getVulnerabilities() {
    return vulnerabilities;
  }

  public void setVulnerabilities(List<Vulnerability> vulnerabilities) {
    this.vulnerabilities = vulnerabilities;
  }

  public Component project(Project project) {
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @ApiModelProperty(required = true, value = "")
  public Project getProject() {
    return project;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  public Component lastInheritedRiskScore(Double lastInheritedRiskScore) {
    this.lastInheritedRiskScore = lastInheritedRiskScore;
    return this;
  }

   /**
   * Get lastInheritedRiskScore
   * @return lastInheritedRiskScore
  **/
  @ApiModelProperty(value = "")
  public Double getLastInheritedRiskScore() {
    return lastInheritedRiskScore;
  }

  public void setLastInheritedRiskScore(Double lastInheritedRiskScore) {
    this.lastInheritedRiskScore = lastInheritedRiskScore;
  }

  public Component notes(String notes) {
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @ApiModelProperty(value = "")
  public String getNotes() {
    return notes;
  }

  public void setNotes(String notes) {
    this.notes = notes;
  }

  public Component uuid(UUID uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(required = true, value = "")
  public UUID getUuid() {
    return uuid;
  }

  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

  public Component bomRef(String bomRef) {
    this.bomRef = bomRef;
    return this;
  }

   /**
   * Get bomRef
   * @return bomRef
  **/
  @ApiModelProperty(value = "")
  public String getBomRef() {
    return bomRef;
  }

  public void setBomRef(String bomRef) {
    this.bomRef = bomRef;
  }

  public Component metrics(DependencyMetrics metrics) {
    this.metrics = metrics;
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @ApiModelProperty(value = "")
  public DependencyMetrics getMetrics() {
    return metrics;
  }

  public void setMetrics(DependencyMetrics metrics) {
    this.metrics = metrics;
  }

  public Component repositoryMeta(RepositoryMetaComponent repositoryMeta) {
    this.repositoryMeta = repositoryMeta;
    return this;
  }

   /**
   * Get repositoryMeta
   * @return repositoryMeta
  **/
  @ApiModelProperty(value = "")
  public RepositoryMetaComponent getRepositoryMeta() {
    return repositoryMeta;
  }

  public void setRepositoryMeta(RepositoryMetaComponent repositoryMeta) {
    this.repositoryMeta = repositoryMeta;
  }

  public Component usedBy(Integer usedBy) {
    this.usedBy = usedBy;
    return this;
  }

   /**
   * Get usedBy
   * @return usedBy
  **/
  @ApiModelProperty(value = "")
  public Integer getUsedBy() {
    return usedBy;
  }

  public void setUsedBy(Integer usedBy) {
    this.usedBy = usedBy;
  }

  public Component isInternal(Boolean isInternal) {
    this.isInternal = isInternal;
    return this;
  }

   /**
   * Get isInternal
   * @return isInternal
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsInternal() {
    return isInternal;
  }

  public void setIsInternal(Boolean isInternal) {
    this.isInternal = isInternal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Component component = (Component) o;
    return Objects.equals(this.author, component.author) &&
        Objects.equals(this.publisher, component.publisher) &&
        Objects.equals(this.group, component.group) &&
        Objects.equals(this.name, component.name) &&
        Objects.equals(this.version, component.version) &&
        Objects.equals(this.classifier, component.classifier) &&
        Objects.equals(this.filename, component.filename) &&
        Objects.equals(this.extension, component.extension) &&
        Objects.equals(this.md5, component.md5) &&
        Objects.equals(this.sha1, component.sha1) &&
        Objects.equals(this.sha256, component.sha256) &&
        Objects.equals(this.sha384, component.sha384) &&
        Objects.equals(this.sha512, component.sha512) &&
        Objects.equals(this.sha3256, component.sha3256) &&
        Objects.equals(this.sha3384, component.sha3384) &&
        Objects.equals(this.sha3512, component.sha3512) &&
        Objects.equals(this.blake2b256, component.blake2b256) &&
        Objects.equals(this.blake2b384, component.blake2b384) &&
        Objects.equals(this.blake2b512, component.blake2b512) &&
        Objects.equals(this.blake3, component.blake3) &&
        Objects.equals(this.cpe, component.cpe) &&
        Objects.equals(this.purl, component.purl) &&
        Objects.equals(this.purlCoordinates, component.purlCoordinates) &&
        Objects.equals(this.swidTagId, component.swidTagId) &&
        Objects.equals(this.description, component.description) &&
        Objects.equals(this.copyright, component.copyright) &&
        Objects.equals(this.license, component.license) &&
        Objects.equals(this.resolvedLicense, component.resolvedLicense) &&
        Objects.equals(this.directDependencies, component.directDependencies) &&
        Objects.equals(this.parent, component.parent) &&
        Objects.equals(this.children, component.children) &&
        Objects.equals(this.vulnerabilities, component.vulnerabilities) &&
        Objects.equals(this.project, component.project) &&
        Objects.equals(this.lastInheritedRiskScore, component.lastInheritedRiskScore) &&
        Objects.equals(this.notes, component.notes) &&
        Objects.equals(this.uuid, component.uuid) &&
        Objects.equals(this.bomRef, component.bomRef) &&
        Objects.equals(this.metrics, component.metrics) &&
        Objects.equals(this.repositoryMeta, component.repositoryMeta) &&
        Objects.equals(this.usedBy, component.usedBy) &&
        Objects.equals(this.isInternal, component.isInternal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, publisher, group, name, version, classifier, filename, extension, md5, sha1, sha256, sha384, sha512, sha3256, sha3384, sha3512, blake2b256, blake2b384, blake2b512, blake3, cpe, purl, purlCoordinates, swidTagId, description, copyright, license, resolvedLicense, directDependencies, parent, children, vulnerabilities, project, lastInheritedRiskScore, notes, uuid, bomRef, metrics, repositoryMeta, usedBy, isInternal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Component {\n");
    
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    publisher: ").append(toIndentedString(publisher)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    classifier: ").append(toIndentedString(classifier)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    md5: ").append(toIndentedString(md5)).append("\n");
    sb.append("    sha1: ").append(toIndentedString(sha1)).append("\n");
    sb.append("    sha256: ").append(toIndentedString(sha256)).append("\n");
    sb.append("    sha384: ").append(toIndentedString(sha384)).append("\n");
    sb.append("    sha512: ").append(toIndentedString(sha512)).append("\n");
    sb.append("    sha3256: ").append(toIndentedString(sha3256)).append("\n");
    sb.append("    sha3384: ").append(toIndentedString(sha3384)).append("\n");
    sb.append("    sha3512: ").append(toIndentedString(sha3512)).append("\n");
    sb.append("    blake2b256: ").append(toIndentedString(blake2b256)).append("\n");
    sb.append("    blake2b384: ").append(toIndentedString(blake2b384)).append("\n");
    sb.append("    blake2b512: ").append(toIndentedString(blake2b512)).append("\n");
    sb.append("    blake3: ").append(toIndentedString(blake3)).append("\n");
    sb.append("    cpe: ").append(toIndentedString(cpe)).append("\n");
    sb.append("    purl: ").append(toIndentedString(purl)).append("\n");
    sb.append("    purlCoordinates: ").append(toIndentedString(purlCoordinates)).append("\n");
    sb.append("    swidTagId: ").append(toIndentedString(swidTagId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    copyright: ").append(toIndentedString(copyright)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    resolvedLicense: ").append(toIndentedString(resolvedLicense)).append("\n");
    sb.append("    directDependencies: ").append(toIndentedString(directDependencies)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    vulnerabilities: ").append(toIndentedString(vulnerabilities)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    lastInheritedRiskScore: ").append(toIndentedString(lastInheritedRiskScore)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    bomRef: ").append(toIndentedString(bomRef)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    repositoryMeta: ").append(toIndentedString(repositoryMeta)).append("\n");
    sb.append("    usedBy: ").append(toIndentedString(usedBy)).append("\n");
    sb.append("    isInternal: ").append(toIndentedString(isInternal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

