/*
 * Copyright 2021 Artem Godin.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Dependency-Track API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * NotificationPublisher
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-21T09:42:21.596Z")
public class NotificationPublisher {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("publisherClass")
  private String publisherClass = null;

  @SerializedName("template")
  private String template = null;

  @SerializedName("templateMimeType")
  private String templateMimeType = null;

  @SerializedName("defaultPublisher")
  private Boolean defaultPublisher = null;

  @SerializedName("uuid")
  private UUID uuid = null;

  public NotificationPublisher name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public NotificationPublisher description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public NotificationPublisher publisherClass(String publisherClass) {
    this.publisherClass = publisherClass;
    return this;
  }

   /**
   * Get publisherClass
   * @return publisherClass
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPublisherClass() {
    return publisherClass;
  }

  public void setPublisherClass(String publisherClass) {
    this.publisherClass = publisherClass;
  }

  public NotificationPublisher template(String template) {
    this.template = template;
    return this;
  }

   /**
   * Get template
   * @return template
  **/
  @ApiModelProperty(value = "")
  public String getTemplate() {
    return template;
  }

  public void setTemplate(String template) {
    this.template = template;
  }

  public NotificationPublisher templateMimeType(String templateMimeType) {
    this.templateMimeType = templateMimeType;
    return this;
  }

   /**
   * Get templateMimeType
   * @return templateMimeType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTemplateMimeType() {
    return templateMimeType;
  }

  public void setTemplateMimeType(String templateMimeType) {
    this.templateMimeType = templateMimeType;
  }

  public NotificationPublisher defaultPublisher(Boolean defaultPublisher) {
    this.defaultPublisher = defaultPublisher;
    return this;
  }

   /**
   * Get defaultPublisher
   * @return defaultPublisher
  **/
  @ApiModelProperty(value = "")
  public Boolean isDefaultPublisher() {
    return defaultPublisher;
  }

  public void setDefaultPublisher(Boolean defaultPublisher) {
    this.defaultPublisher = defaultPublisher;
  }

  public NotificationPublisher uuid(UUID uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(required = true, value = "")
  public UUID getUuid() {
    return uuid;
  }

  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationPublisher notificationPublisher = (NotificationPublisher) o;
    return Objects.equals(this.name, notificationPublisher.name) &&
        Objects.equals(this.description, notificationPublisher.description) &&
        Objects.equals(this.publisherClass, notificationPublisher.publisherClass) &&
        Objects.equals(this.template, notificationPublisher.template) &&
        Objects.equals(this.templateMimeType, notificationPublisher.templateMimeType) &&
        Objects.equals(this.defaultPublisher, notificationPublisher.defaultPublisher) &&
        Objects.equals(this.uuid, notificationPublisher.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, publisherClass, template, templateMimeType, defaultPublisher, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationPublisher {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    publisherClass: ").append(toIndentedString(publisherClass)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    templateMimeType: ").append(toIndentedString(templateMimeType)).append("\n");
    sb.append("    defaultPublisher: ").append(toIndentedString(defaultPublisher)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

