/*
 * Copyright 2021 Artem Godin.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Dependency-Track API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PortfolioMetrics
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-21T09:42:21.596Z")
public class PortfolioMetrics {
  @SerializedName("critical")
  private Integer critical = null;

  @SerializedName("high")
  private Integer high = null;

  @SerializedName("medium")
  private Integer medium = null;

  @SerializedName("low")
  private Integer low = null;

  @SerializedName("unassigned")
  private Integer unassigned = null;

  @SerializedName("vulnerabilities")
  private Integer vulnerabilities = null;

  @SerializedName("projects")
  private Integer projects = null;

  @SerializedName("vulnerableProjects")
  private Integer vulnerableProjects = null;

  @SerializedName("components")
  private Integer components = null;

  @SerializedName("vulnerableComponents")
  private Integer vulnerableComponents = null;

  @SerializedName("suppressed")
  private Integer suppressed = null;

  @SerializedName("findingsTotal")
  private Integer findingsTotal = null;

  @SerializedName("findingsAudited")
  private Integer findingsAudited = null;

  @SerializedName("findingsUnaudited")
  private Integer findingsUnaudited = null;

  @SerializedName("inheritedRiskScore")
  private Double inheritedRiskScore = null;

  @SerializedName("policyViolationsFail")
  private Integer policyViolationsFail = null;

  @SerializedName("policyViolationsWarn")
  private Integer policyViolationsWarn = null;

  @SerializedName("policyViolationsInfo")
  private Integer policyViolationsInfo = null;

  @SerializedName("policyViolationsTotal")
  private Integer policyViolationsTotal = null;

  @SerializedName("policyViolationsAudited")
  private Integer policyViolationsAudited = null;

  @SerializedName("policyViolationsUnaudited")
  private Integer policyViolationsUnaudited = null;

  @SerializedName("policyViolationsSecurityTotal")
  private Integer policyViolationsSecurityTotal = null;

  @SerializedName("policyViolationsSecurityAudited")
  private Integer policyViolationsSecurityAudited = null;

  @SerializedName("policyViolationsSecurityUnaudited")
  private Integer policyViolationsSecurityUnaudited = null;

  @SerializedName("policyViolationsLicenseTotal")
  private Integer policyViolationsLicenseTotal = null;

  @SerializedName("policyViolationsLicenseAudited")
  private Integer policyViolationsLicenseAudited = null;

  @SerializedName("policyViolationsLicenseUnaudited")
  private Integer policyViolationsLicenseUnaudited = null;

  @SerializedName("policyViolationsOperationalTotal")
  private Integer policyViolationsOperationalTotal = null;

  @SerializedName("policyViolationsOperationalAudited")
  private Integer policyViolationsOperationalAudited = null;

  @SerializedName("policyViolationsOperationalUnaudited")
  private Integer policyViolationsOperationalUnaudited = null;

  @SerializedName("firstOccurrence")
  private Double firstOccurrence = null;

  @SerializedName("lastOccurrence")
  private Double lastOccurrence = null;

  public PortfolioMetrics critical(Integer critical) {
    this.critical = critical;
    return this;
  }

   /**
   * Get critical
   * @return critical
  **/
  @ApiModelProperty(value = "")
  public Integer getCritical() {
    return critical;
  }

  public void setCritical(Integer critical) {
    this.critical = critical;
  }

  public PortfolioMetrics high(Integer high) {
    this.high = high;
    return this;
  }

   /**
   * Get high
   * @return high
  **/
  @ApiModelProperty(value = "")
  public Integer getHigh() {
    return high;
  }

  public void setHigh(Integer high) {
    this.high = high;
  }

  public PortfolioMetrics medium(Integer medium) {
    this.medium = medium;
    return this;
  }

   /**
   * Get medium
   * @return medium
  **/
  @ApiModelProperty(value = "")
  public Integer getMedium() {
    return medium;
  }

  public void setMedium(Integer medium) {
    this.medium = medium;
  }

  public PortfolioMetrics low(Integer low) {
    this.low = low;
    return this;
  }

   /**
   * Get low
   * @return low
  **/
  @ApiModelProperty(value = "")
  public Integer getLow() {
    return low;
  }

  public void setLow(Integer low) {
    this.low = low;
  }

  public PortfolioMetrics unassigned(Integer unassigned) {
    this.unassigned = unassigned;
    return this;
  }

   /**
   * Get unassigned
   * @return unassigned
  **/
  @ApiModelProperty(value = "")
  public Integer getUnassigned() {
    return unassigned;
  }

  public void setUnassigned(Integer unassigned) {
    this.unassigned = unassigned;
  }

  public PortfolioMetrics vulnerabilities(Integer vulnerabilities) {
    this.vulnerabilities = vulnerabilities;
    return this;
  }

   /**
   * Get vulnerabilities
   * @return vulnerabilities
  **/
  @ApiModelProperty(value = "")
  public Integer getVulnerabilities() {
    return vulnerabilities;
  }

  public void setVulnerabilities(Integer vulnerabilities) {
    this.vulnerabilities = vulnerabilities;
  }

  public PortfolioMetrics projects(Integer projects) {
    this.projects = projects;
    return this;
  }

   /**
   * Get projects
   * @return projects
  **/
  @ApiModelProperty(value = "")
  public Integer getProjects() {
    return projects;
  }

  public void setProjects(Integer projects) {
    this.projects = projects;
  }

  public PortfolioMetrics vulnerableProjects(Integer vulnerableProjects) {
    this.vulnerableProjects = vulnerableProjects;
    return this;
  }

   /**
   * Get vulnerableProjects
   * @return vulnerableProjects
  **/
  @ApiModelProperty(value = "")
  public Integer getVulnerableProjects() {
    return vulnerableProjects;
  }

  public void setVulnerableProjects(Integer vulnerableProjects) {
    this.vulnerableProjects = vulnerableProjects;
  }

  public PortfolioMetrics components(Integer components) {
    this.components = components;
    return this;
  }

   /**
   * Get components
   * @return components
  **/
  @ApiModelProperty(value = "")
  public Integer getComponents() {
    return components;
  }

  public void setComponents(Integer components) {
    this.components = components;
  }

  public PortfolioMetrics vulnerableComponents(Integer vulnerableComponents) {
    this.vulnerableComponents = vulnerableComponents;
    return this;
  }

   /**
   * Get vulnerableComponents
   * @return vulnerableComponents
  **/
  @ApiModelProperty(value = "")
  public Integer getVulnerableComponents() {
    return vulnerableComponents;
  }

  public void setVulnerableComponents(Integer vulnerableComponents) {
    this.vulnerableComponents = vulnerableComponents;
  }

  public PortfolioMetrics suppressed(Integer suppressed) {
    this.suppressed = suppressed;
    return this;
  }

   /**
   * Get suppressed
   * @return suppressed
  **/
  @ApiModelProperty(value = "")
  public Integer getSuppressed() {
    return suppressed;
  }

  public void setSuppressed(Integer suppressed) {
    this.suppressed = suppressed;
  }

  public PortfolioMetrics findingsTotal(Integer findingsTotal) {
    this.findingsTotal = findingsTotal;
    return this;
  }

   /**
   * Get findingsTotal
   * @return findingsTotal
  **/
  @ApiModelProperty(value = "")
  public Integer getFindingsTotal() {
    return findingsTotal;
  }

  public void setFindingsTotal(Integer findingsTotal) {
    this.findingsTotal = findingsTotal;
  }

  public PortfolioMetrics findingsAudited(Integer findingsAudited) {
    this.findingsAudited = findingsAudited;
    return this;
  }

   /**
   * Get findingsAudited
   * @return findingsAudited
  **/
  @ApiModelProperty(value = "")
  public Integer getFindingsAudited() {
    return findingsAudited;
  }

  public void setFindingsAudited(Integer findingsAudited) {
    this.findingsAudited = findingsAudited;
  }

  public PortfolioMetrics findingsUnaudited(Integer findingsUnaudited) {
    this.findingsUnaudited = findingsUnaudited;
    return this;
  }

   /**
   * Get findingsUnaudited
   * @return findingsUnaudited
  **/
  @ApiModelProperty(value = "")
  public Integer getFindingsUnaudited() {
    return findingsUnaudited;
  }

  public void setFindingsUnaudited(Integer findingsUnaudited) {
    this.findingsUnaudited = findingsUnaudited;
  }

  public PortfolioMetrics inheritedRiskScore(Double inheritedRiskScore) {
    this.inheritedRiskScore = inheritedRiskScore;
    return this;
  }

   /**
   * Get inheritedRiskScore
   * @return inheritedRiskScore
  **/
  @ApiModelProperty(value = "")
  public Double getInheritedRiskScore() {
    return inheritedRiskScore;
  }

  public void setInheritedRiskScore(Double inheritedRiskScore) {
    this.inheritedRiskScore = inheritedRiskScore;
  }

  public PortfolioMetrics policyViolationsFail(Integer policyViolationsFail) {
    this.policyViolationsFail = policyViolationsFail;
    return this;
  }

   /**
   * Get policyViolationsFail
   * @return policyViolationsFail
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsFail() {
    return policyViolationsFail;
  }

  public void setPolicyViolationsFail(Integer policyViolationsFail) {
    this.policyViolationsFail = policyViolationsFail;
  }

  public PortfolioMetrics policyViolationsWarn(Integer policyViolationsWarn) {
    this.policyViolationsWarn = policyViolationsWarn;
    return this;
  }

   /**
   * Get policyViolationsWarn
   * @return policyViolationsWarn
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsWarn() {
    return policyViolationsWarn;
  }

  public void setPolicyViolationsWarn(Integer policyViolationsWarn) {
    this.policyViolationsWarn = policyViolationsWarn;
  }

  public PortfolioMetrics policyViolationsInfo(Integer policyViolationsInfo) {
    this.policyViolationsInfo = policyViolationsInfo;
    return this;
  }

   /**
   * Get policyViolationsInfo
   * @return policyViolationsInfo
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsInfo() {
    return policyViolationsInfo;
  }

  public void setPolicyViolationsInfo(Integer policyViolationsInfo) {
    this.policyViolationsInfo = policyViolationsInfo;
  }

  public PortfolioMetrics policyViolationsTotal(Integer policyViolationsTotal) {
    this.policyViolationsTotal = policyViolationsTotal;
    return this;
  }

   /**
   * Get policyViolationsTotal
   * @return policyViolationsTotal
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsTotal() {
    return policyViolationsTotal;
  }

  public void setPolicyViolationsTotal(Integer policyViolationsTotal) {
    this.policyViolationsTotal = policyViolationsTotal;
  }

  public PortfolioMetrics policyViolationsAudited(Integer policyViolationsAudited) {
    this.policyViolationsAudited = policyViolationsAudited;
    return this;
  }

   /**
   * Get policyViolationsAudited
   * @return policyViolationsAudited
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsAudited() {
    return policyViolationsAudited;
  }

  public void setPolicyViolationsAudited(Integer policyViolationsAudited) {
    this.policyViolationsAudited = policyViolationsAudited;
  }

  public PortfolioMetrics policyViolationsUnaudited(Integer policyViolationsUnaudited) {
    this.policyViolationsUnaudited = policyViolationsUnaudited;
    return this;
  }

   /**
   * Get policyViolationsUnaudited
   * @return policyViolationsUnaudited
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsUnaudited() {
    return policyViolationsUnaudited;
  }

  public void setPolicyViolationsUnaudited(Integer policyViolationsUnaudited) {
    this.policyViolationsUnaudited = policyViolationsUnaudited;
  }

  public PortfolioMetrics policyViolationsSecurityTotal(Integer policyViolationsSecurityTotal) {
    this.policyViolationsSecurityTotal = policyViolationsSecurityTotal;
    return this;
  }

   /**
   * Get policyViolationsSecurityTotal
   * @return policyViolationsSecurityTotal
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsSecurityTotal() {
    return policyViolationsSecurityTotal;
  }

  public void setPolicyViolationsSecurityTotal(Integer policyViolationsSecurityTotal) {
    this.policyViolationsSecurityTotal = policyViolationsSecurityTotal;
  }

  public PortfolioMetrics policyViolationsSecurityAudited(Integer policyViolationsSecurityAudited) {
    this.policyViolationsSecurityAudited = policyViolationsSecurityAudited;
    return this;
  }

   /**
   * Get policyViolationsSecurityAudited
   * @return policyViolationsSecurityAudited
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsSecurityAudited() {
    return policyViolationsSecurityAudited;
  }

  public void setPolicyViolationsSecurityAudited(Integer policyViolationsSecurityAudited) {
    this.policyViolationsSecurityAudited = policyViolationsSecurityAudited;
  }

  public PortfolioMetrics policyViolationsSecurityUnaudited(Integer policyViolationsSecurityUnaudited) {
    this.policyViolationsSecurityUnaudited = policyViolationsSecurityUnaudited;
    return this;
  }

   /**
   * Get policyViolationsSecurityUnaudited
   * @return policyViolationsSecurityUnaudited
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsSecurityUnaudited() {
    return policyViolationsSecurityUnaudited;
  }

  public void setPolicyViolationsSecurityUnaudited(Integer policyViolationsSecurityUnaudited) {
    this.policyViolationsSecurityUnaudited = policyViolationsSecurityUnaudited;
  }

  public PortfolioMetrics policyViolationsLicenseTotal(Integer policyViolationsLicenseTotal) {
    this.policyViolationsLicenseTotal = policyViolationsLicenseTotal;
    return this;
  }

   /**
   * Get policyViolationsLicenseTotal
   * @return policyViolationsLicenseTotal
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsLicenseTotal() {
    return policyViolationsLicenseTotal;
  }

  public void setPolicyViolationsLicenseTotal(Integer policyViolationsLicenseTotal) {
    this.policyViolationsLicenseTotal = policyViolationsLicenseTotal;
  }

  public PortfolioMetrics policyViolationsLicenseAudited(Integer policyViolationsLicenseAudited) {
    this.policyViolationsLicenseAudited = policyViolationsLicenseAudited;
    return this;
  }

   /**
   * Get policyViolationsLicenseAudited
   * @return policyViolationsLicenseAudited
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsLicenseAudited() {
    return policyViolationsLicenseAudited;
  }

  public void setPolicyViolationsLicenseAudited(Integer policyViolationsLicenseAudited) {
    this.policyViolationsLicenseAudited = policyViolationsLicenseAudited;
  }

  public PortfolioMetrics policyViolationsLicenseUnaudited(Integer policyViolationsLicenseUnaudited) {
    this.policyViolationsLicenseUnaudited = policyViolationsLicenseUnaudited;
    return this;
  }

   /**
   * Get policyViolationsLicenseUnaudited
   * @return policyViolationsLicenseUnaudited
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsLicenseUnaudited() {
    return policyViolationsLicenseUnaudited;
  }

  public void setPolicyViolationsLicenseUnaudited(Integer policyViolationsLicenseUnaudited) {
    this.policyViolationsLicenseUnaudited = policyViolationsLicenseUnaudited;
  }

  public PortfolioMetrics policyViolationsOperationalTotal(Integer policyViolationsOperationalTotal) {
    this.policyViolationsOperationalTotal = policyViolationsOperationalTotal;
    return this;
  }

   /**
   * Get policyViolationsOperationalTotal
   * @return policyViolationsOperationalTotal
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsOperationalTotal() {
    return policyViolationsOperationalTotal;
  }

  public void setPolicyViolationsOperationalTotal(Integer policyViolationsOperationalTotal) {
    this.policyViolationsOperationalTotal = policyViolationsOperationalTotal;
  }

  public PortfolioMetrics policyViolationsOperationalAudited(Integer policyViolationsOperationalAudited) {
    this.policyViolationsOperationalAudited = policyViolationsOperationalAudited;
    return this;
  }

   /**
   * Get policyViolationsOperationalAudited
   * @return policyViolationsOperationalAudited
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsOperationalAudited() {
    return policyViolationsOperationalAudited;
  }

  public void setPolicyViolationsOperationalAudited(Integer policyViolationsOperationalAudited) {
    this.policyViolationsOperationalAudited = policyViolationsOperationalAudited;
  }

  public PortfolioMetrics policyViolationsOperationalUnaudited(Integer policyViolationsOperationalUnaudited) {
    this.policyViolationsOperationalUnaudited = policyViolationsOperationalUnaudited;
    return this;
  }

   /**
   * Get policyViolationsOperationalUnaudited
   * @return policyViolationsOperationalUnaudited
  **/
  @ApiModelProperty(value = "")
  public Integer getPolicyViolationsOperationalUnaudited() {
    return policyViolationsOperationalUnaudited;
  }

  public void setPolicyViolationsOperationalUnaudited(Integer policyViolationsOperationalUnaudited) {
    this.policyViolationsOperationalUnaudited = policyViolationsOperationalUnaudited;
  }

  public PortfolioMetrics firstOccurrence(Double firstOccurrence) {
    this.firstOccurrence = firstOccurrence;
    return this;
  }

   /**
   * Get firstOccurrence
   * @return firstOccurrence
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getFirstOccurrence() {
    return firstOccurrence;
  }

  public void setFirstOccurrence(Double firstOccurrence) {
    this.firstOccurrence = firstOccurrence;
  }

  public PortfolioMetrics lastOccurrence(Double lastOccurrence) {
    this.lastOccurrence = lastOccurrence;
    return this;
  }

   /**
   * Get lastOccurrence
   * @return lastOccurrence
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getLastOccurrence() {
    return lastOccurrence;
  }

  public void setLastOccurrence(Double lastOccurrence) {
    this.lastOccurrence = lastOccurrence;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PortfolioMetrics portfolioMetrics = (PortfolioMetrics) o;
    return Objects.equals(this.critical, portfolioMetrics.critical) &&
        Objects.equals(this.high, portfolioMetrics.high) &&
        Objects.equals(this.medium, portfolioMetrics.medium) &&
        Objects.equals(this.low, portfolioMetrics.low) &&
        Objects.equals(this.unassigned, portfolioMetrics.unassigned) &&
        Objects.equals(this.vulnerabilities, portfolioMetrics.vulnerabilities) &&
        Objects.equals(this.projects, portfolioMetrics.projects) &&
        Objects.equals(this.vulnerableProjects, portfolioMetrics.vulnerableProjects) &&
        Objects.equals(this.components, portfolioMetrics.components) &&
        Objects.equals(this.vulnerableComponents, portfolioMetrics.vulnerableComponents) &&
        Objects.equals(this.suppressed, portfolioMetrics.suppressed) &&
        Objects.equals(this.findingsTotal, portfolioMetrics.findingsTotal) &&
        Objects.equals(this.findingsAudited, portfolioMetrics.findingsAudited) &&
        Objects.equals(this.findingsUnaudited, portfolioMetrics.findingsUnaudited) &&
        Objects.equals(this.inheritedRiskScore, portfolioMetrics.inheritedRiskScore) &&
        Objects.equals(this.policyViolationsFail, portfolioMetrics.policyViolationsFail) &&
        Objects.equals(this.policyViolationsWarn, portfolioMetrics.policyViolationsWarn) &&
        Objects.equals(this.policyViolationsInfo, portfolioMetrics.policyViolationsInfo) &&
        Objects.equals(this.policyViolationsTotal, portfolioMetrics.policyViolationsTotal) &&
        Objects.equals(this.policyViolationsAudited, portfolioMetrics.policyViolationsAudited) &&
        Objects.equals(this.policyViolationsUnaudited, portfolioMetrics.policyViolationsUnaudited) &&
        Objects.equals(this.policyViolationsSecurityTotal, portfolioMetrics.policyViolationsSecurityTotal) &&
        Objects.equals(this.policyViolationsSecurityAudited, portfolioMetrics.policyViolationsSecurityAudited) &&
        Objects.equals(this.policyViolationsSecurityUnaudited, portfolioMetrics.policyViolationsSecurityUnaudited) &&
        Objects.equals(this.policyViolationsLicenseTotal, portfolioMetrics.policyViolationsLicenseTotal) &&
        Objects.equals(this.policyViolationsLicenseAudited, portfolioMetrics.policyViolationsLicenseAudited) &&
        Objects.equals(this.policyViolationsLicenseUnaudited, portfolioMetrics.policyViolationsLicenseUnaudited) &&
        Objects.equals(this.policyViolationsOperationalTotal, portfolioMetrics.policyViolationsOperationalTotal) &&
        Objects.equals(this.policyViolationsOperationalAudited, portfolioMetrics.policyViolationsOperationalAudited) &&
        Objects.equals(this.policyViolationsOperationalUnaudited, portfolioMetrics.policyViolationsOperationalUnaudited) &&
        Objects.equals(this.firstOccurrence, portfolioMetrics.firstOccurrence) &&
        Objects.equals(this.lastOccurrence, portfolioMetrics.lastOccurrence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(critical, high, medium, low, unassigned, vulnerabilities, projects, vulnerableProjects, components, vulnerableComponents, suppressed, findingsTotal, findingsAudited, findingsUnaudited, inheritedRiskScore, policyViolationsFail, policyViolationsWarn, policyViolationsInfo, policyViolationsTotal, policyViolationsAudited, policyViolationsUnaudited, policyViolationsSecurityTotal, policyViolationsSecurityAudited, policyViolationsSecurityUnaudited, policyViolationsLicenseTotal, policyViolationsLicenseAudited, policyViolationsLicenseUnaudited, policyViolationsOperationalTotal, policyViolationsOperationalAudited, policyViolationsOperationalUnaudited, firstOccurrence, lastOccurrence);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PortfolioMetrics {\n");
    
    sb.append("    critical: ").append(toIndentedString(critical)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    medium: ").append(toIndentedString(medium)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    unassigned: ").append(toIndentedString(unassigned)).append("\n");
    sb.append("    vulnerabilities: ").append(toIndentedString(vulnerabilities)).append("\n");
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    vulnerableProjects: ").append(toIndentedString(vulnerableProjects)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    vulnerableComponents: ").append(toIndentedString(vulnerableComponents)).append("\n");
    sb.append("    suppressed: ").append(toIndentedString(suppressed)).append("\n");
    sb.append("    findingsTotal: ").append(toIndentedString(findingsTotal)).append("\n");
    sb.append("    findingsAudited: ").append(toIndentedString(findingsAudited)).append("\n");
    sb.append("    findingsUnaudited: ").append(toIndentedString(findingsUnaudited)).append("\n");
    sb.append("    inheritedRiskScore: ").append(toIndentedString(inheritedRiskScore)).append("\n");
    sb.append("    policyViolationsFail: ").append(toIndentedString(policyViolationsFail)).append("\n");
    sb.append("    policyViolationsWarn: ").append(toIndentedString(policyViolationsWarn)).append("\n");
    sb.append("    policyViolationsInfo: ").append(toIndentedString(policyViolationsInfo)).append("\n");
    sb.append("    policyViolationsTotal: ").append(toIndentedString(policyViolationsTotal)).append("\n");
    sb.append("    policyViolationsAudited: ").append(toIndentedString(policyViolationsAudited)).append("\n");
    sb.append("    policyViolationsUnaudited: ").append(toIndentedString(policyViolationsUnaudited)).append("\n");
    sb.append("    policyViolationsSecurityTotal: ").append(toIndentedString(policyViolationsSecurityTotal)).append("\n");
    sb.append("    policyViolationsSecurityAudited: ").append(toIndentedString(policyViolationsSecurityAudited)).append("\n");
    sb.append("    policyViolationsSecurityUnaudited: ").append(toIndentedString(policyViolationsSecurityUnaudited)).append("\n");
    sb.append("    policyViolationsLicenseTotal: ").append(toIndentedString(policyViolationsLicenseTotal)).append("\n");
    sb.append("    policyViolationsLicenseAudited: ").append(toIndentedString(policyViolationsLicenseAudited)).append("\n");
    sb.append("    policyViolationsLicenseUnaudited: ").append(toIndentedString(policyViolationsLicenseUnaudited)).append("\n");
    sb.append("    policyViolationsOperationalTotal: ").append(toIndentedString(policyViolationsOperationalTotal)).append("\n");
    sb.append("    policyViolationsOperationalAudited: ").append(toIndentedString(policyViolationsOperationalAudited)).append("\n");
    sb.append("    policyViolationsOperationalUnaudited: ").append(toIndentedString(policyViolationsOperationalUnaudited)).append("\n");
    sb.append("    firstOccurrence: ").append(toIndentedString(firstOccurrence)).append("\n");
    sb.append("    lastOccurrence: ").append(toIndentedString(lastOccurrence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

