/*
 * Copyright 2021 Artem Godin.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Dependency-Track API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.fluorumlabs.dtrack.model.Vulnerability;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * VulnerableSoftware
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-21T09:42:21.596Z")
public class VulnerableSoftware {
  @SerializedName("purl")
  private String purl = null;

  @SerializedName("purlType")
  private String purlType = null;

  @SerializedName("purlNamespace")
  private String purlNamespace = null;

  @SerializedName("purlName")
  private String purlName = null;

  @SerializedName("purlVersion")
  private String purlVersion = null;

  @SerializedName("purlQualifiers")
  private String purlQualifiers = null;

  @SerializedName("purlSubpath")
  private String purlSubpath = null;

  @SerializedName("cpe22")
  private String cpe22 = null;

  @SerializedName("cpe23")
  private String cpe23 = null;

  @SerializedName("part")
  private String part = null;

  @SerializedName("vendor")
  private String vendor = null;

  @SerializedName("product")
  private String product = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("update")
  private String update = null;

  @SerializedName("edition")
  private String edition = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("swEdition")
  private String swEdition = null;

  @SerializedName("targetSw")
  private String targetSw = null;

  @SerializedName("targetHw")
  private String targetHw = null;

  @SerializedName("other")
  private String other = null;

  @SerializedName("versionEndExcluding")
  private String versionEndExcluding = null;

  @SerializedName("versionEndIncluding")
  private String versionEndIncluding = null;

  @SerializedName("versionStartExcluding")
  private String versionStartExcluding = null;

  @SerializedName("versionStartIncluding")
  private String versionStartIncluding = null;

  @SerializedName("vulnerabilities")
  private List<Vulnerability> vulnerabilities = null;

  @SerializedName("uuid")
  private UUID uuid = null;

  @SerializedName("isVulnerable")
  private Boolean isVulnerable = null;

  public VulnerableSoftware purl(String purl) {
    this.purl = purl;
    return this;
  }

   /**
   * Get purl
   * @return purl
  **/
  @ApiModelProperty(value = "")
  public String getPurl() {
    return purl;
  }

  public void setPurl(String purl) {
    this.purl = purl;
  }

  public VulnerableSoftware purlType(String purlType) {
    this.purlType = purlType;
    return this;
  }

   /**
   * Get purlType
   * @return purlType
  **/
  @ApiModelProperty(value = "")
  public String getPurlType() {
    return purlType;
  }

  public void setPurlType(String purlType) {
    this.purlType = purlType;
  }

  public VulnerableSoftware purlNamespace(String purlNamespace) {
    this.purlNamespace = purlNamespace;
    return this;
  }

   /**
   * Get purlNamespace
   * @return purlNamespace
  **/
  @ApiModelProperty(value = "")
  public String getPurlNamespace() {
    return purlNamespace;
  }

  public void setPurlNamespace(String purlNamespace) {
    this.purlNamespace = purlNamespace;
  }

  public VulnerableSoftware purlName(String purlName) {
    this.purlName = purlName;
    return this;
  }

   /**
   * Get purlName
   * @return purlName
  **/
  @ApiModelProperty(value = "")
  public String getPurlName() {
    return purlName;
  }

  public void setPurlName(String purlName) {
    this.purlName = purlName;
  }

  public VulnerableSoftware purlVersion(String purlVersion) {
    this.purlVersion = purlVersion;
    return this;
  }

   /**
   * Get purlVersion
   * @return purlVersion
  **/
  @ApiModelProperty(value = "")
  public String getPurlVersion() {
    return purlVersion;
  }

  public void setPurlVersion(String purlVersion) {
    this.purlVersion = purlVersion;
  }

  public VulnerableSoftware purlQualifiers(String purlQualifiers) {
    this.purlQualifiers = purlQualifiers;
    return this;
  }

   /**
   * Get purlQualifiers
   * @return purlQualifiers
  **/
  @ApiModelProperty(value = "")
  public String getPurlQualifiers() {
    return purlQualifiers;
  }

  public void setPurlQualifiers(String purlQualifiers) {
    this.purlQualifiers = purlQualifiers;
  }

  public VulnerableSoftware purlSubpath(String purlSubpath) {
    this.purlSubpath = purlSubpath;
    return this;
  }

   /**
   * Get purlSubpath
   * @return purlSubpath
  **/
  @ApiModelProperty(value = "")
  public String getPurlSubpath() {
    return purlSubpath;
  }

  public void setPurlSubpath(String purlSubpath) {
    this.purlSubpath = purlSubpath;
  }

  public VulnerableSoftware cpe22(String cpe22) {
    this.cpe22 = cpe22;
    return this;
  }

   /**
   * Get cpe22
   * @return cpe22
  **/
  @ApiModelProperty(value = "")
  public String getCpe22() {
    return cpe22;
  }

  public void setCpe22(String cpe22) {
    this.cpe22 = cpe22;
  }

  public VulnerableSoftware cpe23(String cpe23) {
    this.cpe23 = cpe23;
    return this;
  }

   /**
   * Get cpe23
   * @return cpe23
  **/
  @ApiModelProperty(value = "")
  public String getCpe23() {
    return cpe23;
  }

  public void setCpe23(String cpe23) {
    this.cpe23 = cpe23;
  }

  public VulnerableSoftware part(String part) {
    this.part = part;
    return this;
  }

   /**
   * Get part
   * @return part
  **/
  @ApiModelProperty(value = "")
  public String getPart() {
    return part;
  }

  public void setPart(String part) {
    this.part = part;
  }

  public VulnerableSoftware vendor(String vendor) {
    this.vendor = vendor;
    return this;
  }

   /**
   * Get vendor
   * @return vendor
  **/
  @ApiModelProperty(value = "")
  public String getVendor() {
    return vendor;
  }

  public void setVendor(String vendor) {
    this.vendor = vendor;
  }

  public VulnerableSoftware product(String product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @ApiModelProperty(value = "")
  public String getProduct() {
    return product;
  }

  public void setProduct(String product) {
    this.product = product;
  }

  public VulnerableSoftware version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public VulnerableSoftware update(String update) {
    this.update = update;
    return this;
  }

   /**
   * Get update
   * @return update
  **/
  @ApiModelProperty(value = "")
  public String getUpdate() {
    return update;
  }

  public void setUpdate(String update) {
    this.update = update;
  }

  public VulnerableSoftware edition(String edition) {
    this.edition = edition;
    return this;
  }

   /**
   * Get edition
   * @return edition
  **/
  @ApiModelProperty(value = "")
  public String getEdition() {
    return edition;
  }

  public void setEdition(String edition) {
    this.edition = edition;
  }

  public VulnerableSoftware language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public VulnerableSoftware swEdition(String swEdition) {
    this.swEdition = swEdition;
    return this;
  }

   /**
   * Get swEdition
   * @return swEdition
  **/
  @ApiModelProperty(value = "")
  public String getSwEdition() {
    return swEdition;
  }

  public void setSwEdition(String swEdition) {
    this.swEdition = swEdition;
  }

  public VulnerableSoftware targetSw(String targetSw) {
    this.targetSw = targetSw;
    return this;
  }

   /**
   * Get targetSw
   * @return targetSw
  **/
  @ApiModelProperty(value = "")
  public String getTargetSw() {
    return targetSw;
  }

  public void setTargetSw(String targetSw) {
    this.targetSw = targetSw;
  }

  public VulnerableSoftware targetHw(String targetHw) {
    this.targetHw = targetHw;
    return this;
  }

   /**
   * Get targetHw
   * @return targetHw
  **/
  @ApiModelProperty(value = "")
  public String getTargetHw() {
    return targetHw;
  }

  public void setTargetHw(String targetHw) {
    this.targetHw = targetHw;
  }

  public VulnerableSoftware other(String other) {
    this.other = other;
    return this;
  }

   /**
   * Get other
   * @return other
  **/
  @ApiModelProperty(value = "")
  public String getOther() {
    return other;
  }

  public void setOther(String other) {
    this.other = other;
  }

  public VulnerableSoftware versionEndExcluding(String versionEndExcluding) {
    this.versionEndExcluding = versionEndExcluding;
    return this;
  }

   /**
   * Get versionEndExcluding
   * @return versionEndExcluding
  **/
  @ApiModelProperty(value = "")
  public String getVersionEndExcluding() {
    return versionEndExcluding;
  }

  public void setVersionEndExcluding(String versionEndExcluding) {
    this.versionEndExcluding = versionEndExcluding;
  }

  public VulnerableSoftware versionEndIncluding(String versionEndIncluding) {
    this.versionEndIncluding = versionEndIncluding;
    return this;
  }

   /**
   * Get versionEndIncluding
   * @return versionEndIncluding
  **/
  @ApiModelProperty(value = "")
  public String getVersionEndIncluding() {
    return versionEndIncluding;
  }

  public void setVersionEndIncluding(String versionEndIncluding) {
    this.versionEndIncluding = versionEndIncluding;
  }

  public VulnerableSoftware versionStartExcluding(String versionStartExcluding) {
    this.versionStartExcluding = versionStartExcluding;
    return this;
  }

   /**
   * Get versionStartExcluding
   * @return versionStartExcluding
  **/
  @ApiModelProperty(value = "")
  public String getVersionStartExcluding() {
    return versionStartExcluding;
  }

  public void setVersionStartExcluding(String versionStartExcluding) {
    this.versionStartExcluding = versionStartExcluding;
  }

  public VulnerableSoftware versionStartIncluding(String versionStartIncluding) {
    this.versionStartIncluding = versionStartIncluding;
    return this;
  }

   /**
   * Get versionStartIncluding
   * @return versionStartIncluding
  **/
  @ApiModelProperty(value = "")
  public String getVersionStartIncluding() {
    return versionStartIncluding;
  }

  public void setVersionStartIncluding(String versionStartIncluding) {
    this.versionStartIncluding = versionStartIncluding;
  }

  public VulnerableSoftware vulnerabilities(List<Vulnerability> vulnerabilities) {
    this.vulnerabilities = vulnerabilities;
    return this;
  }

  public VulnerableSoftware addVulnerabilitiesItem(Vulnerability vulnerabilitiesItem) {
    if (this.vulnerabilities == null) {
      this.vulnerabilities = new ArrayList<>();
    }
    this.vulnerabilities.add(vulnerabilitiesItem);
    return this;
  }

   /**
   * Get vulnerabilities
   * @return vulnerabilities
  **/
  @ApiModelProperty(value = "")
  public List<Vulnerability> getVulnerabilities() {
    return vulnerabilities;
  }

  public void setVulnerabilities(List<Vulnerability> vulnerabilities) {
    this.vulnerabilities = vulnerabilities;
  }

  public VulnerableSoftware uuid(UUID uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public UUID getUuid() {
    return uuid;
  }

  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

  public VulnerableSoftware isVulnerable(Boolean isVulnerable) {
    this.isVulnerable = isVulnerable;
    return this;
  }

   /**
   * Get isVulnerable
   * @return isVulnerable
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsVulnerable() {
    return isVulnerable;
  }

  public void setIsVulnerable(Boolean isVulnerable) {
    this.isVulnerable = isVulnerable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VulnerableSoftware vulnerableSoftware = (VulnerableSoftware) o;
    return Objects.equals(this.purl, vulnerableSoftware.purl) &&
        Objects.equals(this.purlType, vulnerableSoftware.purlType) &&
        Objects.equals(this.purlNamespace, vulnerableSoftware.purlNamespace) &&
        Objects.equals(this.purlName, vulnerableSoftware.purlName) &&
        Objects.equals(this.purlVersion, vulnerableSoftware.purlVersion) &&
        Objects.equals(this.purlQualifiers, vulnerableSoftware.purlQualifiers) &&
        Objects.equals(this.purlSubpath, vulnerableSoftware.purlSubpath) &&
        Objects.equals(this.cpe22, vulnerableSoftware.cpe22) &&
        Objects.equals(this.cpe23, vulnerableSoftware.cpe23) &&
        Objects.equals(this.part, vulnerableSoftware.part) &&
        Objects.equals(this.vendor, vulnerableSoftware.vendor) &&
        Objects.equals(this.product, vulnerableSoftware.product) &&
        Objects.equals(this.version, vulnerableSoftware.version) &&
        Objects.equals(this.update, vulnerableSoftware.update) &&
        Objects.equals(this.edition, vulnerableSoftware.edition) &&
        Objects.equals(this.language, vulnerableSoftware.language) &&
        Objects.equals(this.swEdition, vulnerableSoftware.swEdition) &&
        Objects.equals(this.targetSw, vulnerableSoftware.targetSw) &&
        Objects.equals(this.targetHw, vulnerableSoftware.targetHw) &&
        Objects.equals(this.other, vulnerableSoftware.other) &&
        Objects.equals(this.versionEndExcluding, vulnerableSoftware.versionEndExcluding) &&
        Objects.equals(this.versionEndIncluding, vulnerableSoftware.versionEndIncluding) &&
        Objects.equals(this.versionStartExcluding, vulnerableSoftware.versionStartExcluding) &&
        Objects.equals(this.versionStartIncluding, vulnerableSoftware.versionStartIncluding) &&
        Objects.equals(this.vulnerabilities, vulnerableSoftware.vulnerabilities) &&
        Objects.equals(this.uuid, vulnerableSoftware.uuid) &&
        Objects.equals(this.isVulnerable, vulnerableSoftware.isVulnerable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(purl, purlType, purlNamespace, purlName, purlVersion, purlQualifiers, purlSubpath, cpe22, cpe23, part, vendor, product, version, update, edition, language, swEdition, targetSw, targetHw, other, versionEndExcluding, versionEndIncluding, versionStartExcluding, versionStartIncluding, vulnerabilities, uuid, isVulnerable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VulnerableSoftware {\n");
    
    sb.append("    purl: ").append(toIndentedString(purl)).append("\n");
    sb.append("    purlType: ").append(toIndentedString(purlType)).append("\n");
    sb.append("    purlNamespace: ").append(toIndentedString(purlNamespace)).append("\n");
    sb.append("    purlName: ").append(toIndentedString(purlName)).append("\n");
    sb.append("    purlVersion: ").append(toIndentedString(purlVersion)).append("\n");
    sb.append("    purlQualifiers: ").append(toIndentedString(purlQualifiers)).append("\n");
    sb.append("    purlSubpath: ").append(toIndentedString(purlSubpath)).append("\n");
    sb.append("    cpe22: ").append(toIndentedString(cpe22)).append("\n");
    sb.append("    cpe23: ").append(toIndentedString(cpe23)).append("\n");
    sb.append("    part: ").append(toIndentedString(part)).append("\n");
    sb.append("    vendor: ").append(toIndentedString(vendor)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    update: ").append(toIndentedString(update)).append("\n");
    sb.append("    edition: ").append(toIndentedString(edition)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    swEdition: ").append(toIndentedString(swEdition)).append("\n");
    sb.append("    targetSw: ").append(toIndentedString(targetSw)).append("\n");
    sb.append("    targetHw: ").append(toIndentedString(targetHw)).append("\n");
    sb.append("    other: ").append(toIndentedString(other)).append("\n");
    sb.append("    versionEndExcluding: ").append(toIndentedString(versionEndExcluding)).append("\n");
    sb.append("    versionEndIncluding: ").append(toIndentedString(versionEndIncluding)).append("\n");
    sb.append("    versionStartExcluding: ").append(toIndentedString(versionStartExcluding)).append("\n");
    sb.append("    versionStartIncluding: ").append(toIndentedString(versionStartIncluding)).append("\n");
    sb.append("    vulnerabilities: ").append(toIndentedString(vulnerabilities)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    isVulnerable: ").append(toIndentedString(isVulnerable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

